@ECHO OFF
CHCP 936>NUL
CD /D "%~DP0"
FOR /F "TOKENS=2 DELIMS=," %%I IN ('TYPE CONFIG.INI') DO (COLOR %%I)
TITLE 进程文件定位器
CLS
SETLOCAL ENABLEDELAYEDEXPANSION
GOTO A

:A
SET N=0
CLS
ECHO 进程文件定位器主面板
ECHO 请选定定位方式:
ECHO   0=退出程序
ECHO   1=通过映像名称定位
ECHO   2=通过PID定位
ECHO 请选定一种方式：
CHOICE /C 120
IF %ERRORLEVEL%==3 EXIT
GOTO %ERRORLEVEL%

:1
CLS
ECHO 请输入映像名称：
SET /P PROCESSNAME=
CLS
IF /I "%PROCESSNAME%"=="SYSTEM" (GOTO SYSTEM)
IF /I "%PROCESSNAME%"=="SYSTEM IDLE PROCESS" (GOTO IDLE)
ECHO 进程%PROCESSNAME%的映像路径如下：
FOR /F "Skip=1 delims=" %%i in ('WMIC PROCESS WHERE NAME^="%PROCESSNAME%" GET EXECUTABLEPATH') do (@ECHO %%i)
FOR /F "Skip=1 delims=" %%i in ('WMIC PROCESS WHERE NAME^="%PROCESSNAME%" GET EXECUTABLEPATH') do (
	SET /A N=N+1
	SET PATH!N!=%%i
)
GOTO O

:2
CLS
ECHO 请输入PID：
SET /P PROCESSID=
SET /A IDTEMP=%PROCESSID%*1
IF "PROCESSID"=="%IDTEMP%" (GOTO 3)
CLS
IF "%PROCESSID%"=="0" (GOTO IDLE)
IF "%PROCESSID%"=="4" (GOTO SYSTEM)
ECHO PID为%PROCESSID%的进程映像路径如下：
FOR /F "Skip=1 delims=" %%i in ('WMIC PROCESS WHERE PROCESSID^="%PROCESSID%" GET EXECUTABLEPATH') do (@ECHO %%i)
FOR /F "Skip=1 delims=" %%i in ('WMIC PROCESS WHERE PROCESSID^="%PROCESSID%" GET EXECUTABLEPATH') do (
	SET N=1
	SET PATH1=%%i
)
GOTO O

:3
CLS
ECHO 错误的PID！请按任意键返回上一级面板。
PAUSE>NUL
GOTO 2

:IDLE
ECHO 进程System Idle Process为系统空闲进程，无映像路径，
PAUSE
GOTO A

:O
IF %N%==0 (GOTO A)
ECHO 是否打开所在目录？
CHOICE /C YN
IF %ERRORLEVEL%==1 (GOTO Y)
GOTO Z

:SYSTEM
ECHO 进程System的映像路径如下：%SYSTEMROOT%，
SET N=1
SET PATH1=%SYSTEMROOT%
GOTO O

:Y
CALL EXPLORER.EXE /E,/SELECT,"%%PATH%N%%%"
SET /A N=N-1
IF %N%==0 (GOTO Z)
GOTO Y

:Z
ECHO 执行操作完毕，请按任意键返回主面板。
PAUSE>NUL
GOTO A